Repository autowarefoundation/open-ad-kit-docs, pull requests merged in 2022-09, with the labels that each got.

#28 refactor: delete the contents of application example in the version 2.0
  docs/version-2.0/application-example/.pages
  docs/version-2.0/application-example/index.md
Labels: documentation

#29 refactor: delete application example for v1.0
  docs/version-1.0/application-example/.pages
  docs/version-1.0/application-example/index.md
Labels: documentation

#30 refactor: fix typos under system configuration chapter
  docs/version-1.0/system-configuration/index.md
  docs/version-2.0/system-configuration/index.md
Labels: documentation

#33 feat(word): support local spell check
  .cspell.json
  docs/version-2.0/start-guide/installation/index.md
  docs/version-2.0/start-guide/installation/system-setup-pcu.md
Labels: bug, documentation

#32 chore: fix emoji not emoji not rendered
  mkdocs.yaml
Labels: documentation, enhancement
